apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::903449438459:role/eksctl-devops-cluster-nodegroup-wo-NodeInstanceRole-VTGZQbrYZ48K
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::903449438459:user/Manboy
      username: Manboy
      groups:
        - system:masters
    - userarn: arn:aws:iam::903449438459:user/task-app-cicd
      username: task-app-cicd
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-19T22:48:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1409"
  uid: b883665c-fb32-48be-84dc-79682446c1c3
