apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app
  namespace: application
  labels:
    app: task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: task-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          command:
            - sh
            - -c
            - |
              until pg_isready -h task-db -p 5432 -U postgres; do
                echo "En attente de PostgreSQL (task-db)...";
                sleep 3;
              done
              echo "PostgreSQL prêt, démarrage de task-app.";
      containers:
        - name: task-app
          # Cette valeur sera remplacée par Ansible :
          # REMPLACER_PAR_TON_ECR_URI:latest -> <account>.dkr.ecr.<region>.amazonaws.com/task-app:<commit>
          image: REMPLACER_PAR_TON_ECR_URI:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: task-config
            - secretRef:
                name: task-secrets
          # Readiness = app + DB OK
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 3
          # Liveness = process Flask/Gunicorn vivant
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              cpu: "250m"
              memory: "200Mi"
